// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkEKAEdL3F_8U_aihLIOBXfrdx3Hak4vY',
    appId: '1:611945397694:web:bed6afd010f0f2a8794def',
    messagingSenderId: '611945397694',
    projectId: 'iespushnotification',
    authDomain: 'iespushnotification.firebaseapp.com',
    storageBucket: 'iespushnotification.firebasestorage.app',
    measurementId: 'G-JNBJV2MFK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqVETF_ypHCxgr0iLtb29VffgUMHF7PPE',
    appId: '1:611945397694:android:ae687a53c2688f8a794def',
    messagingSenderId: '611945397694',
    projectId: 'iespushnotification',
    storageBucket: 'iespushnotification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADekX2DYhklu--L-3deZyaGEpGmhd6Jog',
    appId: '1:611945397694:ios:d45409cc21485558794def',
    messagingSenderId: '611945397694',
    projectId: 'iespushnotification',
    storageBucket: 'iespushnotification.firebasestorage.app',
    iosBundleId: 'com.example.iesMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADekX2DYhklu--L-3deZyaGEpGmhd6Jog',
    appId: '1:611945397694:ios:d45409cc21485558794def',
    messagingSenderId: '611945397694',
    projectId: 'iespushnotification',
    storageBucket: 'iespushnotification.firebasestorage.app',
    iosBundleId: 'com.example.iesMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkEKAEdL3F_8U_aihLIOBXfrdx3Hak4vY',
    appId: '1:611945397694:web:e1684ec32066a105794def',
    messagingSenderId: '611945397694',
    projectId: 'iespushnotification',
    authDomain: 'iespushnotification.firebaseapp.com',
    storageBucket: 'iespushnotification.firebasestorage.app',
    measurementId: 'G-3V0ZC9V72J',
  );
}
